### ISSUE TITLE
issue in ADD EXPENSES 'name'

### ISSUE THREAD

**Issue by ittid** [amineichou/budgetApp#1]
in the first input in ADD EXPENSES section there a bugs
if I tab the space tab on the keyboard and I fill the information with just spaces without letters they accept the  EXPENSES
so u need to use length.trim() to validate the form and prevent users from sending space value => "                       "

<img width="1103" alt="Capture d’écran 2022-11-07 à 00 19 05" src="https://user-images.githubusercontent.com/44928080/200200873-90706ff4-f73a-4115-a12c-a710215963e7.png">

**Comment by amineichou** [comment]
That's true !!!
Thank you so much

**Comment by ittid** [comment]
u can test the input by this 
`
if ( value.trim() == "" ) {
return;
}
`

**Comment by amineichou** [comment]
Ok, will do that.

**Comment by amineichou** [comment]
i did thanks
